/**
 * Copies the Mana font's CSS (MIT) into src/styles/vendor/mana.css without
 * its @font-face rules. We declare our own @font-face (woff2 only) so the
 * build doesn't ship eot/ttf/svg copies or the bundled MPlantin font.
 *
 *   npm run vendor:mana   (re-run after upgrading mana-font)
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { createRequire } from 'node:module'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const require = createRequire(import.meta.url)
const pkg = require('mana-font/package.json') as { version: string }
const css = await readFile(require.resolve('mana-font/css/mana.css'), 'utf8')

const stripped = css.replace(/@font-face\s*\{[^}]*\}\s*/g, '')
const header = `/*
 * Generated by scripts/vendor-mana-css.ts from mana-font@${pkg.version}. Do not edit.
 * Mana CSS © Andrew Gioia, MIT License. Mana font: SIL OFL 1.1.
 * https://github.com/andrewgioia/mana
 */
`
const out = join(root, 'src/styles/vendor/mana.css')
await mkdir(dirname(out), { recursive: true })
await writeFile(out, header + stripped)
console.log(`Wrote ${out} (${stripped.length} bytes)`)
